### ISSUE TITLE
Waterfox forceclosing on GitHub search

### ISSUE THREAD

**Issue by Hikari-no-Tenshi** [zakius/Polly#12]
HI.
I'm using Poly on Waterfox Classic 2020.10 to access GitHub.
I checked "polyfills/Webcomponents-Bundle.js" but this not always working and often i have to refresh page few times.
Then i checked "Use request modification method for this domain" and i think with this GitHub pages loading better.
But with checked "Use request modification method for this domain" Waterfox forceclosing when i use GitHub search.

**Comment by zakius** [comment]
Hello

I'm sorry to hear you have issues like that, though I don't think it can be caused by my extension alone.
Do you have any other extensions installed? Especially ones interacting with requests? Possibly also MITM performing antivirus software? Could you give it a try on a clean profile with only Polly installed and then slowly keep adding your other extensions and settings? There shouldn't be any interference but we can try pinpointing the source of issues

**Comment by Hikari-no-Tenshi** [comment]
Tried Waterfox with pure profile and have same issue.
With "polyfills/Webcomponents-Bundle.js" GitHub working but often i have to reload pages few times to make it work.
With "Use request modification method for this domain" GitHub seems working better but Waterfox forceclosing when i try to search on GitHub.

**Comment by Hikari-no-Tenshi** [comment]
Interesting thing that Waterfox may close many times in the row but then once successfully load GitHub search results.

**Comment by LeeBinder** [comment]
@Hikari-no-Tenshi excuse my directness here.. why don't you at least provide the OS you are using + the exact version??

I can NOT reproduce that in latest WF Classic 2020.10 macOS, regardless if polly only with Bundle.js enabled for github, or polly + dom.webcomponents.customelements.enabled = true.

**Comment by Hikari-no-Tenshi** [comment]
Windows 10 x64, Waterfox Classic 2020.10 x64.
If i check "polyfills/Webcomponents-Bundle.js" and "Use request modification method for this domain" Waterfox will FC in 99.9% cases when trying to search something on GitHub.
So i'm using only "polyfills/Webcomponents-Bundle.js" but often have to reload pages again and again to make different GitHub functions to work.

**Comment by LeeBinder** [comment]
ah OK, thank you - so this might be a "Polly in Windows" only issue. That might help zakius to narrow down.

Can you double-check in Waterfox Add-Ons/Extension tab that indeed you are using the latest version 1.4? If not, update, test again. If you are, please downgrade Polly to v.1.3, test, and if necessary downgrade all the way to v.1.0 to see if that issue was introduced at some point.

Please share your findings here 👍

**Comment by Hikari-no-Tenshi** [comment]
It is 1.4.
No need to downgrade as i think "Use request modification method for this domain" was introduced in 1.4.
And on other builds i had other issue with Cyrillic characters on some websites.

**Comment by LeeBinder** [comment]
sorry but that's wrong: `Use request modification method for this domain` was already present in v.1.3 (at least in WF Classic macOS), if not earlier. Please downgrade to v.1.3, convince yourself that indeed it it present, test, and report back :)

**Comment by zakius** [comment]
due to the way how many websites work it's pretty much necessity to use request modification as Content Scripts are injected a bit too late during the page load so if any code that requires polyfill is executed during page load it will fail

as of crashes I have no idea what's causing them, WebExtensions API shouldn't even allow anything that can affect browser stability and I've personally never experienced this issue, but I can try narrowing down the issue to find a workaround, though it will require answers to these questions:

- do you use any antivirus software that can interfere with HTTPS connections?
- do you use any legacy extensions, especially ones affecting the network connections? (think: uBlock Origin Legacy, but may be others, possibly classic NoScript? just dropping ideas)
- does this issue happen for you also on new profile?

**Comment by Hikari-no-Tenshi** [comment]
> 
> 
> due to the way how many websites work it's pretty much necessity to use request modification as Content Scripts are injected a bit too late during the page load so if any code that requires polyfill is executed during page load it will fail
> 
> as of crashes I have no idea what's causing them, WebExtensions API shouldn't even allow anything that can affect browser stability and I've personally never experienced this issue, but I can try narrowing down the issue to find a workaround, though it will require answers to these questions:
> 
>     * do you use any antivirus software that can interfere with HTTPS connections?
> 
>     * do you use any legacy extensions, especially ones affecting the network connections? (think: uBlock Origin Legacy, but may be others, possibly classic NoScript? just dropping ideas)
> 
>     * does this issue happen for you also on new profile?

1. ESET Internet Security.
2. uBlock Origin 1.31.0 (disabled for GitHub).
3. Same on clean profile.

**Comment by Squall-Leonhart** [comment]
the problem occurs in a blank slate profile with nothing installed in the system that would affect https connections.

**Comment by Hikari-no-Tenshi** [comment]
With disabled Antivirus and Firewall Waterfox still crashes.

**Comment by zakius** [comment]
as it's happening even on clean profiles with nothing interesting on the system I'm out of ideas

I'll try changing some things up but I can't promise anything, probably will add few more settings so you can choose if support of non-UTF8 is needed for particular domain, unfortunately that's just a guess, I'll let you know when new version is ready

**Comment by Hikari-no-Tenshi** [comment]
Tried on Waterfox Classic 2020.10 x64 on Linux Mint 20 in Virtual Machine.
Waterfox not crashing on GitHub search with enabled "polyfills/Webcomponents-Bundle.js" and "Use request modification method for this domain".
Probably problem only on Windows.

**Comment by zakius** [comment]
After looking at the code again I can't really make toggle for encoding detection as that part of code also makes sure only HTML is modified (without this part code would try to treat every response as document and I don't think it's a good idea to do that and rely on errors instead of performing proper sanity check).

Instead of that I removed some redundant logging used during development and changed re-encoding part to use the native implementation whenever possible (so on GitHub it will be used, not the JS one with non-UTF8 encodings available)

I have no idea if it will be of any help, but as it avoids instantiation of a huge object and uses native, much faster implementation it may help avoiding this issue

**Comment by zakius** [comment]
is anyone still experiencing this issue or it seems to be resolved?

**Comment by Hikari-no-Tenshi** [comment]
For me nothing changed.
On Waterfox 2020.12 Classic with Polly 1.9 still crashing (tried few days ago).

**Comment by zakius** [comment]
At this point there's nothing more I can do I think, it may be helpful to contact Waterfox team, though AFAIK they are working on backporting WebComponents support to Classic so they may be not interested in fixing this issue even if it's on their end

**Comment by Hikari-no-Tenshi** [comment]
It is time to move to newer versions.
More and more websites are getting broken on Waterfox Classic.
I'm using it only because of FindBar-Tweak extension.

**Comment by zakius** [comment]
as update:

I encountered freezes on GutHub in different scenario recently but still have no idea what's happening

and today I stumbled upon https://github.com/JustOff/github-wc-polyfill that's bootstrapped extension (so may be able to overcome some WE issues) that's made specifically to inject required polyfill for GitHub so you may try that

**Comment by JustOff** [comment]
Please note that `github-wc-polyfill` requires e10s to be disabled as Mozilla failed to fix [bug #1261585](https://bugzilla.mozilla.org/show_bug.cgi?id=1261585).
