### ISSUE TITLE
1.2 Corrupts Certain Downloads

### ISSUE THREAD

**Issue by naqaden** [zakius/Polly#2]
After updating to 1.2, certain jar archives I download end up inflating beyond their original file size. I just noticed it with Minecraft mods and haven't been able to reproduce it on other file types. Example: [https://www.curseforge.com/minecraft/mc-mods/dynamictrees/download/3062957/file](https://www.curseforge.com/minecraft/mc-mods/dynamictrees/download/3062957/file) should be 821KB but ends up 1.27MB when I save it. This happens to every mod jar I've tested from CurseForge.

If I host the same jar on my personal domain and download from there, it still inflates but not as much. These domains shouldn't be affected or behave differently since I'm only injecting pollyfills on github and imgur. I tried toggling polyfills anyway but it didn't help.

Reverting to 1.1 solves the problem so I'm sticking with that for now.

**Comment by zakius** [comment]
I'll look into it, most likely will only register event for domains you chose to use request modification method of injection. I'm still not sure how to apply filter only for HTML documents, probably will have to look at contents as at this moment of request lifecycle response headers are not available.

I'm sorry for the trouble

**Comment by KandiPanda** [comment]
I encountered what seems to be similar issues with 1.2, and can confirm that it's 1.2 doing it (removing Polly and/or reverting to 1.1 and then restarting the browser - must restart! - fixes the issue.)

Test cases: 
- Going to https://derpibooru.org/images/2352165 and clicking the "View" or "VS" should open the video directly. Instead, with 1.2 installed, it shows an error that it can't be played.
- PNG images on multiple sites (https://cdn.discordapp.com/attachments/379954405166022656/767147224156078150/c5hf5ccz4ot51.png as one example) were saying that they were unable to be display due to errors when 1.2 was installed.

**Comment by zakius** [comment]
I'll soon release version preventing this issue from happening on websites that are not `request mode` enabled, but for ones that are I'll need more time

**Comment by zakius** [comment]
1.3 should fix these issues, even if domain needs polyfills as non-HTML responses shouldn't be affected, but I'm leaving this open for a while in case you experience any more issues like that

**Comment by Purfview** [comment]
1.2 is breaking popup menus of some other plugins, but it's fixed with 1.3. Just letting you know that there was such bug.
Thanks for this cool plugin.

**Comment by naqaden** [comment]
Yep, 1.3 has fixed my download issues. Thank you @zakius!
